// src/views/empleado/DashboardView.jsx
import { useState, useEffect } from 'react';
import { Calendar, Activity, Target, Award } from 'lucide-react';
import Layout from '../../components/layout/Layout';
import StatsCard from '../../components/ui/StatsCard';
import DataTable from '../../components/ui/DataTable';
import { supabase } from '../../services/supabase';
import { useAuth } from '../../context/AuthContext';
import { format } from 'date-fns';
import { es } from 'date-fns/locale';

const DashboardView = () => {
  const { user } = useAuth();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [stats, setStats] = useState({
    proximasSesiones: 0,
    puntosAcumulados: 0,
    desafiosActivos: 0,
    logrosObtenidos: 0
  });
  const [proximasSesiones, setProximasSesiones] = useState([]);
  const [desafiosActivos, setDesafiosActivos] = useState([]);
  const [ultimosLogros, setUltimosLogros] = useState([]);

  useEffect(() => {
    const loadDashboardData = async () => {
      try {
        setLoading(true);
        
        // Cargar próximas sesiones
        const { data: sesiones, error: sesionesError } = await supabase
          .from('reservas')
          .select(`
            id,
            sesion:sesiones (
              id,
              titulo,
              fecha_inicio,
              fecha_fin,
              modalidad,
              usuarios:colaborador_id (
                nombre,
                apellido
              ),
              servicios (
                nombre,
                tipo
              )
            )
          `)
          .eq('usuario_id', user.id)
          .eq('estado', 'confirmada')
          .gte('sesion.fecha_inicio', new Date().toISOString())
          .order('sesion.fecha_inicio')
          .limit(5);

        if (sesionesError) throw sesionesError;

        // Cargar puntos acumulados
        const { data: perfil, error: perfilError } = await supabase
          .from('perfil_empleados')
          .select('puntos_bienestar')
          .eq('usuario_id', user.id)
          .single();

        if (perfilError) throw perfilError;

        // Cargar desafíos activos
        const { data: desafios, error: desafiosError } = await supabase
          .from('participacion_desafios')
          .select(`
            id,
            desafio:desafios_bienestar (
              id,
              titulo,
              descripcion,
              fecha_fin,
              puntos_completar
            )
          `)
          .eq('usuario_id', user.id)
          .in('estado', ['inscrito', 'en_progreso'])
          .order('desafio.fecha_fin')
          .limit(5);

        if (desafiosError) throw desafiosError;

        // Cargar últimos logros
        const { data: logros, error: logrosError } = await supabase
          .from('logros_usuario')
          .select(`
            id,
            fecha_obtencion,
            puntos_otorgados,
            logro:catalogo_logros (
              titulo,
              descripcion,
              categoria
            )
          `)
          .eq('usuario_id', user.id)
          .order('fecha_obtencion', { ascending: false })
          .limit(5);

        if (logrosError) throw logrosError;

        setStats({
          proximasSesiones: sesiones?.length || 0,
          puntosAcumulados: perfil?.puntos_bienestar || 0,
          desafiosActivos: desafios?.length || 0,
          logrosObtenidos: logros?.length || 0
        });

        setProximasSesiones(sesiones || []);
        setDesafiosActivos(desafios || []);
        setUltimosLogros(logros || []);
      } catch (err) {
        console.error('Error al cargar datos del dashboard:', err);
        setError('Error al cargar los datos del dashboard');
      } finally {
        setLoading(false);
      }
    };

    loadDashboardData();
  }, [user?.id]);

  if (error) {
    return (
      <Layout>
        <div className="text-red-600 bg-red-50 p-4 rounded-lg">
          {error}
        </div>
      </Layout>
    );
  }

  return (
    <Layout>
      <div className="space-y-8">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">
            ¡Bienvenido, {user?.nombre}!
          </h1>
          <p className="mt-1 text-sm text-gray-500">
            Aquí tienes un resumen de tu bienestar
          </p>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <StatsCard
            title="Próximas Sesiones"
            value={stats.proximasSesiones}
            icon={<Calendar className="h-6 w-6 text-primary" />}
          />
          <StatsCard
            title="Puntos Acumulados"
            value={stats.puntosAcumulados}
            icon={<Activity className="h-6 w-6 text-primary" />}
          />
          <StatsCard
            title="Desafíos Activos"
            value={stats.desafiosActivos}
            icon={<Target className="h-6 w-6 text-primary" />}
          />
          <StatsCard
            title="Logros Obtenidos"
            value={stats.logrosObtenidos}
            icon={<Award className="h-6 w-6 text-primary" />}
          />
        </div>

        {/* Content Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Próximas Sesiones */}
          <div>
            <h2 className="text-lg font-semibold text-gray-900 mb-4">
              Próximas Sesiones
            </h2>
            <DataTable
              columns={[
                {
                  key: 'titulo',
                  header: 'Sesión',
                  render: (row) => row.sesion.titulo
                },
                {
                  key: 'fecha',
                  header: 'Fecha',
                  render: (row) => format(
                    new Date(row.sesion.fecha_inicio),
                    'PPp',
                    { locale: es }
                  )
                },
                {
                  key: 'colaborador',
                  header: 'Colaborador',
                  render: (row) => `${row.sesion.usuarios.nombre} ${row.sesion.usuarios.apellido}`
                }
              ]}
              data={proximasSesiones}
              searchable={false}
              pagination={false}
            />
          </div>

          {/* Desafíos Activos */}
          <div>
            <h2 className="text-lg font-semibold text-gray-900 mb-4">
              Desafíos Activos
            </h2>
            <DataTable
              columns={[
                {
                  key: 'titulo',
                  header: 'Desafío',
                  render: (row) => row.desafio.titulo
                },
                {
                  key: 'fecha_fin',
                  header: 'Finaliza',
                  render: (row) => format(
                    new Date(row.desafio.fecha_fin),
                    'PP',
                    { locale: es }
                  )
                },
                {
                  key: 'puntos',
                  header: 'Puntos',
                  render: (row) => row.desafio.puntos_completar
                }
              ]}
              data={desafiosActivos}
              searchable={false}
              pagination={false}
            />
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default DashboardView;

// src/views/superadmin/DashboardView.vue
<template>
  <div class="space-y-8">
    <!-- Header -->
    <div>
      <h1 class="text-2xl font-bold text-gray-900">Dashboard Superadmin</h1>
      <p class="mt-1 text-sm text-gray-500">
        Vista general del sistema
      </p>
    </div>

    <!-- Stats Grid -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
      <StatsCard
        title="Total Empresas"
        :value="stats.totalEmpresas"
        icon="Building2"
        trend="neutral"
      />
      <StatsCard
        title="Total Usuarios"
        :value="stats.totalUsuarios"
        icon="Users"
        trend="up"
      />
      <StatsCard
        title="Colaboradores Pendientes"
        :value="stats.colaboradoresPendientes"
        icon="UserCheck"
        trend="neutral"
      />
      <StatsCard
        title="Sesiones Hoy"
        :value="stats.sesionesHoy"
        icon="Calendar"
        trend="neutral"
      />
    </div>

    <!-- Tables Grid -->
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
      <!-- Empresas Recientes -->
      <div>
        <h2 class="text-lg font-semibold text-gray-900 mb-4">
          Empresas Recientes
        </h2>
        <DataTable
          :columns="[
            { key: 'nombre', header: 'Nombre' },
            { key: 'dominio_email', header: 'Dominio' },
            {
              key: 'activo',
              header: 'Estado',
              render: (row) => ({
                text: row.activo ? 'Activa' : 'Inactiva',
                class: row.activo ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'
              })
            }
          ]"
          :data="empresasRecientes"
          searchable={false}
          pagination={false}
        />
      </div>

      <!-- Colaboradores Pendientes -->
      <div>
        <h2 class="text-lg font-semibold text-gray-900 mb-4">
          Colaboradores Pendientes
        </h2>
        <DataTable
          :columns="[
            {
              key: 'nombre',
              header: 'Nombre',
              render: (row) => `${row.usuarios.nombre} ${row.usuarios.apellido}`
            },
            {
              key: 'email',
              header: 'Email',
              render: (row) => row.usuarios.email
            },
            { key: 'especialidad', header: 'Especialidad' }
          ]"
          :data="colaboradoresPendientes"
          searchable={false}
          pagination={false}
        />
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import { Building2, Users, UserCheck, Calendar } from 'lucide-vue-next';
import { supabase } from '../../services/supabase';
import StatsCard from '../../components/common/StatsCard.vue';
import DataTable from '../../components/common/DataTable.vue';

const stats = ref({
  totalEmpresas: 0,
  totalUsuarios: 0,
  colaboradoresPendientes: 0,
  sesionesHoy: 0
});

const empresasRecientes = ref([]);
const colaboradoresPendientes = ref([]);

const loadDashboardData = async () => {
  try {
    // Cargar estadísticas
    const [
      { count: empresasCount },
      { count: usuariosCount },
      { count: colaboradoresCount },
      { count: sesionesCount }
    ] = await Promise.all([
      supabase.from('empresas').select('*', { count: 'exact', head: true }),
      supabase.from('usuarios').select('*', { count: 'exact', head: true }),
      supabase
        .from('perfil_colaboradores')
        .select('*', { count: 'exact', head: true })
        .eq('estado', 'pendiente'),
      supabase
        .from('sesiones')
        .select('*', { count: 'exact', head: true })
        .gte('fecha_inicio', new Date().toISOString().split('T')[0])
        .lte('fecha_inicio', new Date().toISOString().split('T')[0] + 'T23:59:59')
    ]);

    stats.value = {
      totalEmpresas: empresasCount || 0,
      totalUsuarios: usuariosCount || 0,
      colaboradoresPendientes: colaboradoresCount || 0,
      sesionesHoy: sesionesCount || 0
    };

    // Cargar empresas recientes
    const { data: empresas } = await supabase
      .from('empresas')
      .select('*')
      .order('fecha_registro', { ascending: false })
      .limit(5);

    empresasRecientes.value = empresas || [];

    // ✅ CONSULTA CORREGIDA - Cargar colaboradores pendientes
    const { data: colaboradoresList, error: colaboradoresError } = await supabase
      .from('perfil_colaboradores')
      .select('*')
      .eq('estado', 'pendiente')
      .limit(5);

    let colaboradores = [];

    if (!colaboradoresError && colaboradoresList && colaboradoresList.length > 0) {
      // Obtener datos de usuarios por separado
      const usuarioIds = colaboradoresList.map(c => c.usuario_id);
      const { data: usuariosData } = await supabase
        .from('usuarios')
        .select('id, nombre, apellido, email')
        .in('id', usuarioIds);

      // Combinar los datos
      colaboradores = colaboradoresList.map(colab => ({
        ...colab,
        usuarios: usuariosData?.find(u => u.id === colab.usuario_id) || {
          nombre: 'Sin datos',
          apellido: '',
          email: 'No disponible'
        }
      }));
    }

    colaboradoresPendientes.value = colaboradores;
  } catch (error) {
    console.error('Error loading dashboard data:', error);
  }
};

onMounted(() => {
  loadDashboardData();
});
</script>
