// src/views/colaborador/DashboardView.vue
<template>
  <div class="space-y-8">
    <!-- Header -->
    <div>
      <h1 class="text-2xl font-bold text-gray-900">
        ¡Bienvenido, {{ authStore.user?.nombre }}!
      </h1>
      <p class="mt-1 text-sm text-gray-500">
        Aquí tienes un resumen de tus actividades
      </p>
    </div>

    <!-- Stats Grid -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
      <StatsCard
        title="Sesiones Hoy"
        :value="stats.sesionesHoy"
        :icon="Calendar"
      />
      <StatsCard
        title="Calificación Promedio"
        :value="stats.calificacionPromedio"
        :icon="Star"
      />
      <StatsCard
        title="Clientes Activos"
        :value="stats.clientesActivos"
        :icon="Users"
      />
      <StatsCard
        title="Sesiones Completadas"
        :value="stats.sesionesCompletadas"
        :icon="TrendingUp"
      />
    </div>

    <!-- Content Grid -->
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
      <!-- Próximas Sesiones -->
      <div>
        <h2 class="text-lg font-semibold text-gray-900 mb-4">
          Próximas Sesiones
        </h2>
        <DataTable
          :columns="[
            { key: 'titulo', header: 'Sesión' },
            {
              key: 'fecha',
              header: 'Fecha',
              render: (row) => formatDate(row.fecha_inicio)
            },
            {
              key: 'empresa',
              header: 'Empresa',
              render: (row) => row.empresas?.nombre || 'Privada'
            }
          ]"
          :data="proximasSesiones"
          :loading="loading"
          searchable={false}
          pagination={false}
        />
      </div>

      <!-- Últimas Calificaciones -->
      <div>
        <h2 class="text-lg font-semibold text-gray-900 mb-4">
          Últimas Calificaciones
        </h2>
        <DataTable
          :columns="[
            {
              key: 'sesion',
              header: 'Sesión',
              render: (row) => row.sesiones?.titulo
            },
            {
              key: 'calificacion',
              header: 'Calificación',
              render: (row) => (
                row.calificacion_general
              )
            },
            {
              key: 'fecha',
              header: 'Fecha',
              render: (row) => formatDate(row.fecha_feedback, 'short')
            }
          ]"
          :data="ultimasCalificaciones"
          :loading="loading"
          searchable={false}
          pagination={false}
        />
      </div>

      <!-- Sesiones Personalizadas -->
      <div class="lg:col-span-2">
        <h2 class="text-lg font-semibold text-gray-900 mb-4">
          Sesiones Personalizadas Pendientes
        </h2>
        <DataTable
          :columns="[
            { key: 'titulo', header: 'Título' },
            { key: 'tipo_sesion', header: 'Tipo' },
            {
              key: 'cliente',
              header: 'Cliente',
              render: (row) => `${row.usuarios.nombre} ${row.usuarios.apellido}`
            },
            {
              key: 'fecha',
              header: 'Fecha',
              render: (row) => row.fecha_sesion ? formatDate(row.fecha_sesion, 'short') : 'Por confirmar'
            }
          ]"
          :data="sesionesPersonalizadas"
          :loading="loading"
          searchable={false}
          pagination={false}
        />
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import { Calendar, Star, Users, TrendingUp } from 'lucide-vue-next';
import { useAuthStore } from '../../stores/auth.store';
import { supabase } from '../../services/supabase';
import StatsCard from '../../components/common/StatsCard.vue';
import DataTable from '../../components/common/DataTable.vue';

const authStore = useAuthStore();
const loading = ref(true);

const stats = ref({
  sesionesHoy: 0,
  calificacionPromedio: 0,
  clientesActivos: 0,
  sesionesCompletadas: 0
});

const proximasSesiones = ref([]);
const ultimasCalificaciones = ref([]);
const sesionesPersonalizadas = ref([]);

const formatDate = (dateString, format = 'long') => {
  const date = new Date(dateString);
  const options = format === 'long' 
    ? {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      }
    : {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      };
  
  return date.toLocaleDateString('es-ES', options);
};

const loadDashboardData = async () => {
  try {
    loading.value = true;

    // Cargar próximas sesiones
    const { data: sesiones } = await supabase
      .from('sesiones')
      .select(`
        id,
        titulo,
        fecha_inicio,
        fecha_fin,
        modalidad,
        empresas (
          nombre
        )
      `)
      .eq('colaborador_id', authStore.user.id)
      .eq('estado_sesion', 'programada')
      .gte('fecha_inicio', new Date().toISOString())
      .order('fecha_inicio')
      .limit(5);

    // Cargar últimas calificaciones
    const { data: calificaciones } = await supabase
      .from('feedback_detallado')
      .select(`
        id,
        fecha_feedback,
        calificacion_general,
        calificacion_colaborador,
        comentario_general,
        sesiones (
          titulo
        )
      `)
      .eq('colaborador_id', authStore.user.id)
      .order('fecha_feedback', { ascending: false })
      .limit(5);

    // Calcular promedio de calificaciones
    const promedio = calificaciones?.length
      ? calificaciones.reduce((acc, curr) => acc + curr.calificacion_general, 0) / calificaciones.length
      : 0;

    // ✅ CONSULTA CORREGIDA - Cargar sesiones personalizadas pendientes
    const { data: personalizadasList, error: personalizadasError } = await supabase
      .from('sesiones_personalizadas')
      .select('*')
      .eq('colaborador_id', authStore.user.id)
      .in('estado', ['solicitada', 'confirmada'])
      .order('fecha_sesion')
      .limit(5);

    let personalizadas = [];

    if (!personalizadasError && personalizadasList && personalizadasList.length > 0) {
      // Obtener datos de usuarios por separado
      const usuarioIds = personalizadasList.map(p => p.usuario_id);
      const { data: usuariosData } = await supabase
        .from('usuarios')
        .select('id, nombre, apellido')
        .in('id', usuarioIds);

      // Combinar los datos
      personalizadas = personalizadasList.map(sesion => ({
        ...sesion,
        usuarios: usuariosData?.find(u => u.id === sesion.usuario_id) || {
          nombre: 'Sin datos',
          apellido: ''
        }
      }));
    }

    // Contar sesiones de hoy
    const sesionesHoy = sesiones?.filter(s => 
      new Date(s.fecha_inicio).toDateString() === new Date().toDateString()
    ).length || 0;

    // Contar clientes activos (usuarios únicos con reservas activas)
    const { data: reservas } = await supabase
      .from('reservas')
      .select('usuario_id')
      .eq('sesion.colaborador_id', authStore.user.id)
      .eq('estado', 'confirmada')
      .not('asistio', 'is', true);

    const clientesUnicos = new Set(reservas?.map(r => r.usuario_id));

    // Contar sesiones completadas
    const { count: completadas } = await supabase
      .from('sesiones')
      .select('id', { count: 'exact', head: true })
      .eq('colaborador_id', authStore.user.id)
      .eq('estado_sesion', 'completada');

    stats.value = {
      sesionesHoy,
      calificacionPromedio: Number(promedio.toFixed(1)),
      clientesActivos: clientesUnicos.size,
      sesionesCompletadas: completadas || 0
    };

    proximasSesiones.value = sesiones || [];
    ultimasCalificaciones.value = calificaciones || [];
    sesionesPersonalizadas.value = personalizadas;
  } catch (error) {
    console.error('Error loading dashboard data:', error);
  } finally {
    loading.value = false;
  }
};

onMounted(() => {
  loadDashboardData();
});
</script>

// src/views/empleado/DashboardView.jsx
import { useState, useEffect } from 'react';
import { Calendar, Activity, Target, Award } from 'lucide-react';
import Layout from '../../components/layout/Layout';
import StatsCard from '../../components/ui/StatsCard';
import DataTable from '../../components/ui/DataTable';
import { supabase } from '../../services/supabase';
import { useAuth } from '../../context/AuthContext';
import { format } from 'date-fns';
import { es } from 'date-fns/locale';

const DashboardView = () => {
  const { user } = useAuth();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [stats, setStats] = useState({
    proximasSesiones: 0,
    puntosAcumulados: 0,
    desafiosActivos: 0,
    logrosObtenidos: 0
  });
  const [proximasSesiones, setProximasSesiones] = useState([]);
  const [desafiosActivos, setDesafiosActivos] = useState([]);
  const [ultimosLogros, setUltimosLogros] = useState([]);

  useEffect(() => {
    const loadDashboardData = async () => {
      try {
        setLoading(true);
        
        // Cargar próximas sesiones
        const { data: sesiones, error: sesionesError } = await supabase
          .from('reservas')
          .select(`
            id,
            sesion:sesiones (
              id,
              titulo,
              fecha_inicio,
              fecha_fin,
              modalidad,
              usuarios:colaborador_id (
                nombre,
                apellido
              ),
              servicios (
                nombre,
                tipo
              )
            )
          `)
          .eq('usuario_id', user.id)
          .eq('estado', 'confirmada')
          .gte('sesion.fecha_inicio', new Date().toISOString())
          .order('sesion.fecha_inicio')
          .limit(5);

        if (sesionesError) throw sesionesError;

        // Cargar puntos acumulados
        const { data: perfil, error: perfilError } = await supabase
          .from('perfil_empleados')
          .select('puntos_bienestar')
          .eq('usuario_id', user.id)
          .single();

        if (perfilError) throw perfilError;

        // Cargar desafíos activos
        const { data: desafios, error: desafiosError } = await supabase
          .from('participacion_desafios')
          .select(`
            id,
            desafio:desafios_bienestar (
              id,
              titulo,
              descripcion,
              fecha_fin,
              puntos_completar
            )
          `)
          .eq('usuario_id', user.id)
          .in('estado', ['inscrito', 'en_progreso'])
          .order('desafio.fecha_fin')
          .limit(5);

        if (desafiosError) throw desafiosError;

        // Cargar últimos logros
        const { data: logros, error: logrosError } = await supabase
          .from('logros_usuario')
          .select(`
            id,
            fecha_obtencion,
            puntos_otorgados,
            logro:catalogo_logros (
              titulo,
              descripcion,
              categoria
            )
          `)
          .eq('usuario_id', user.id)
          .order('fecha_obtencion', { ascending: false })
          .limit(5);

        if (logrosError) throw logrosError;

        setStats({
          proximasSesiones: sesiones?.length || 0,
          puntosAcumulados: perfil?.puntos_bienestar || 0,
          desafiosActivos: desafios?.length || 0,
          logrosObtenidos: logros?.length || 0
        });

        setProximasSesiones(sesiones || []);
        setDesafiosActivos(desafios || []);
        setUltimosLogros(logros || []);
      } catch (err) {
        console.error('Error al cargar datos del dashboard:', err);
        setError('Error al cargar los datos del dashboard');
      } finally {
        setLoading(false);
      }
    };

    loadDashboardData();
  }, [user?.id]);

  if (error) {
    return (
      <Layout>
        <div className="text-red-600 bg-red-50 p-4 rounded-lg">
          {error}
        </div>
      </Layout>
    );
  }

  return (
    <Layout>
      <div className="space-y-8">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">
            ¡Bienvenido, {user?.nombre}!
          </h1>
          <p className="mt-1 text-sm text-gray-500">
            Aquí tienes un resumen de tu bienestar
          </p>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <StatsCard
            title="Próximas Sesiones"
            value={stats.proximasSesiones}
            icon={<Calendar className="h-6 w-6 text-primary" />}
          />
          <StatsCard
            title="Puntos Acumulados"
            value={stats.puntosAcumulados}
            icon={<Activity className="h-6 w-6 text-primary" />}
          />
          <StatsCard
            title="Desafíos Activos"
            value={stats.desafiosActivos}
            icon={<Target className="h-6 w-6 text-primary" />}
          />
          <StatsCard
            title="Logros Obtenidos"
            value={stats.logrosObtenidos}
            icon={<Award className="h-6 w-6 text-primary" />}
          />
        </div>

        {/* Content Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Próximas Sesiones */}
          <div>
            <h2 className="text-lg font-semibold text-gray-900 mb-4">
              Próximas Sesiones
            </h2>
            <DataTable
              columns={[
                {
                  key: 'titulo',
                  header: 'Sesión',
                  render: (row) => row.sesion.titulo
                },
                {
                  key: 'fecha',
                  header: 'Fecha',
                  render: (row) => format(
                    new Date(row.sesion.fecha_inicio),
                    'PPp',
                    { locale: es }
                  )
                },
                {
                  key: 'colaborador',
                  header: 'Colaborador',
                  render: (row) => `${row.sesion.usuarios.nombre} ${row.sesion.usuarios.apellido}`
                }
              ]}
              data={proximasSesiones}
              searchable={false}
              pagination={false}
            />
          </div>

          {/* Desafíos Activos */}
          <div>
            <h2 className="text-lg font-semibold text-gray-900 mb-4">
              Desafíos Activos
            </h2>
            <DataTable
              columns={[
                {
                  key: 'titulo',
                  header: 'Desafío',
                  render: (row) => row.desafio.titulo
                },
                {
                  key: 'fecha_fin',
                  header: 'Finaliza',
                  render: (row) => format(
                    new Date(row.desafio.fecha_fin),
                    'PP',
                    { locale: es }
                  )
                },
                {
                  key: 'puntos',
                  header: 'Puntos',
                  render: (row) => row.desafio.puntos_completar
                }
              ]}
              data={desafiosActivos}
              searchable={false}
              pagination={false}
            />
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default DashboardView;
